### ISSUE TITLE
Theme an app with c#

### ISSUE THREAD

**Issue by wtorricos** [dotnet/docs-maui#1022]
I'm having problems finding information on how to work with styles and themes properly using only C#.
The last part describes that it is possible to change the theming in c# with something like this:

```c#
ICollection<ResourceDictionary> mergedDictionaries = Application.Current.Resources.MergedDictionaries;
if (mergedDictionaries != null)
{
    mergedDictionaries.Clear();
    mergedDictionaries.Add(new DarkTheme());
}
```

However, this is not working currently or probably some additional information is missing.

This is what I did. On a new application using the default MAUI template, I updated the `Resources/Styles/Colors.xaml` file as well as the `Resources/Styles/Styles.xaml` and I added a x:Class attribute to both of them. Something like this:
```
<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Styles.AppColors">
```

Then in the App class I tried adding them without XAML like this:
```c#
public class App : Application
{
    public App()
    {
        MainPage = new AppShell();

        Resources.MergedDictionaries.Add(new Styles.AppColors());
        Resources.MergedDictionaries.Add(new Styles.AppStyles());
    }
}
```
But the styles are not being applied. I'm not sure if this is a bug or if the docs are missing something.

I would prefer to use only C# but I didn't find much information, so I don't even know if it is possible to have implicit styles with C#. That also leads to my next question, is using only C# for theming supported or should I stick with XAML for the moment?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04d29bb3-0ea9-e42a-d6d2-cf338baca362
* Version Independent ID: 04d29bb3-0ea9-e42a-d6d2-cf338baca362
* Content: [Theme an app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/theming#set-a-default-theme)
* Content Source: [docs/user-interface/theming.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/theming.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tico321 

Any XAML can be written as C#. The two things you did are correct (add x:Class to the style file, and your modifications to the App class). It's just that a third step is also necessary.

The rules you need to know are this:

- A ResourceDictionary that defines styles in XAML, and which is consumed only from XAML, doesn't require a code-behind file (e.g. MyResourceDictionary.xaml.cs isn't required).
- A ResourceDictionary that defines styles in XAML, and which is consumed from C#, does require a code-behind file.

The easiest way to modify the two style files to have a code-behind file is to use the ResourceDictionary (XAML) item template in Visual Studio. This will add a XAML-based ResourceDictionary that includes a code-behind file:

![Capture](https://user-images.githubusercontent.com/8092460/197159059-95b58800-a82b-4951-9828-29cbf2e3faf4.PNG)

It's also probably sensible to re-order your code in `App` to:

```
        Resources.MergedDictionaries.Add(new Styles.AppColors());
        Resources.MergedDictionaries.Add(new Styles.AppStyles());

        MainPage = new AppShell();
```

This way, the styles are in place before the app UI is first rendered.

Generally speaking, we've dropped the requirement to include C# versions of everything in the doc, because the vast majority of users are using XAML. However, this is a good nugget of information to include so I'll create a separate issue to track it.

Hope this helps!

**Comment by wtorricos** [comment]
Now is working, thank you!!

Sorry to keep bothering but could you also point me in the right direction on where to report the following issue? 
Visual Studio is not recognizing the call to `InitializeComponent` inside the generated codebehind file and shows a red squiggly line. It's not a showstopper since the project compiles and runs just fine.

**Comment by davidbritch** [comment]
You can report that at https://developercommunity.visualstudio.com. Thanks!
