### ISSUE TITLE
Need more explanations on the difference between modal and modeless navigation

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/docs-maui#1109]
Still don't understand when to use which, after reading through. Maybe attaching some example code could help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2de983b4-92d4-6429-ff72-1b86fde88687
* Version Independent ID: 2de983b4-92d4-6429-ff72-1b86fde88687
* Content: [NavigationPage - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/navigationpage?view=net-maui-7.0)
* Content Source: [docs/user-interface/pages/navigationpage.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pages/navigationpage.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. I don't know that there is like a specific USE THIS WHEN X guide related to this because it really is just about choosing the design you want your user to experience. Having 2 or 3 pages that are related where you want people to easily swap back and forth would probably be a TabPage. If you have a navigation system where one page goes to another and then from there to another and want the user to be able to go back, navigation works well.

Really the introductory paragraph to each page type tells you what it does so you need to just determine for yourself if that's the experience you want.
