### ISSUE TITLE
Issue with VisualStateManager on Windows Platform when Highlighting an Item 

### ISSUE THREAD

**Issue by phmeek** [dotnet/docs-maui#1145]
When using the VisualStateManager to specify the background colour for a selected item in a CollectionView, the background colour changes when clicking on an item, but then then reverts to the original background colour when the cursor is moved away from the control.  I.e. The background colour of the selected row changes to the required colour when I click on one of the items in the CollectionView but the colour is not retained unless the mouse cursor remains over the selected item.

This can be reproduced by creating a new .NET Maui project and just changing the MainPage.xaml as shown in the attached project.
[SelectionTest.zip](https://github.com/dotnet/docs-maui/files/10296421/SelectionTest.zip)

**Comment by gulbanana** [comment]
This happens on Mac Catalyst as well.

**Comment by davidbritch** [comment]
Hi @phmeek 

Afraid this needs logging in the [engineering repo](https://github.com/dotnet/maui) so that the engineers can take a look at it. Thanks!

**Comment by gulbanana** [comment]
This issue is emblematic of the MAUI experience. phmeek first raised this issue on Stack Overflow and was given a nonsensical answer by a team member who didn't seem to understand the question. He was then linked to this repo and urged to raise an issue in it, even though the repro is trivial:
![image](https://user-images.githubusercontent.com/1612285/209891594-a08c26b3-d9b2-43b8-b2f3-e810221ecd26.png)
Five days later, we're told to piss off. The bug remains unfixed, along with thousands of others.

**Comment by davidbritch** [comment]
@gulbanana It still needs logging in the [engineering repo](https://github.com/dotnet/maui). This repo is for issues with docs,  not with the product.
