### ISSUE TITLE
Too much unnecessary information

### ISSUE THREAD

**Issue by fonzane** [dotnet/docs-maui#1217]
I'm playing around and learning .NET Maui. In order to build a simple login form. I wanted to implement two way data binding. A quick, simple and easy example, in code, would have done. Instead I have to read through multiple hundred lines of code out of a working application with tons of superfluous information and detailed information I don't need. This experience was a turn-off and I'm tempted to look for a tutorial somewhere else.

It would be nice to have a quick summary of how the techniques work for advanced programmers at the top and the option to go through everything in detail further below.

Make the information as easy accessible as possible, imo.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97463723-c3a8-0647-d699-ececebdb527f
* Version Independent ID: 97463723-c3a8-0647-d699-ececebdb527f
* Content: [Binding mode - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/binding-mode?view=net-maui-7.0)
* Content Source: [docs/fundamentals/data-binding/binding-mode.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/binding-mode.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @fonzane 

Everyone has different learning styles, and the content we produce has to cater for everyone of all abilities. On top of that we also have to follow Microsoft-recommended approaches, produced by instructional designers, for presenting information in docs. So that's why the docs are how they are.

I'm not meaning to sound dismissive of your suggestion - that would be ideal. But unfortunately our hands are tied on this one.

Thanks for the suggestion.
