### ISSUE TITLE
We should include platforms information for each controls

### ISSUE THREAD

**Issue by Strypper** [dotnet/docs-maui#1219]
![image](https://user-images.githubusercontent.com/32596308/215072720-72b22182-bb39-4fb2-b54a-fdf1db502e84.png)
Can we have `platforms support` for every controls? so that users know what this control will be available on, for example, tooltips and menubar are only available on windows

**Comment by davidbritch** [comment]
Hi @Strypper 

Fundamentally everything is available on every platform, unless the doc specifically calls out that it's not available on a platform. When it's not available on a platform it's generally because the platform doesn't support it.

As for your suggestion, I like it. It's actually something that's being worked on for the API docs, so that you'll see which platforms the type is available on. I suspect it'll be a while before it's rolled out though.

Thanks again for your suggestion.
