### ISSUE TITLE
Why not Microsoft.Data.Sqlite instead of sqlite-net-pcl?

### ISSUE THREAD

**Issue by motmot80** [dotnet/docs-maui#1324]
Hello everyone,

**sqlite-net-pcl** is still missing some **System.Data.Sqlite** features like transactions or datareaders.

Why do you recommend an external lib when microsoft has its own **Microsoft.Data.Sqlite** implementation of SqlitePCLRaw within efcore?

(https://github.com/dotnet/efcore#microsoftdatasqlite)

Best regards
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73164f27-28e1-7bf6-64ec-277ade9ac973
* Version Independent ID: 73164f27-28e1-7bf6-64ec-277ade9ac973
* Content: [.NET MAUI local databases - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/database-sqlite?view=net-maui-7.0)
* Content Source: [docs/data-cloud/database-sqlite.md](https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/database-sqlite.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @motmot80 

That's a very good question and it's took some digging to find out the answer. The external lib was recommended for historical reasons, because there were no alternatives originally. But that's no longer the case - Microsoft.Data.Sqlite now has support.

So provided Microsoft.Data.Sqlite has decent performance we'll be switching to recommending it. However, it'll take a while for investigations to conclude.

**Comment by davidbritch** [comment]
Closing in favour of https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/database-sqlite
