### ISSUE TITLE
Would love a source and recommendation around the AppDataDirectory on an iOS simulator

### ISSUE THREAD

**Issue by rbrettj** [dotnet/docs-maui#1353]
Under Platform Differences, there is an Important note under iOS for the FileSystem.AppDataDirectory that mentions that "the application ID changes with each build so you have to retrieve the correct ID each time you build your application for the simulator". I am trying to debug an issue that deals with this and I would love either a source for this information (I cannot seem to find anything that mentions it online) or a recommendation for how to work around this for writing a file to this directory, and then reading from it on a second run of the app. There must be a way around this, as it seems particularly nasty when testing the ability to save user files (such as game saves) and read them back later.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Version Independent ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Content: [File system helpers - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?view=net-maui-7.0&tabs=ios)
* Content Source: [docs/platform-integration/storage/file-system-helpers.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/file-system-helpers.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 73059](https://dev.azure.com/msft-skilling/Content/_workitems/edit/73059)

**Comment by davidbritch** [comment]
Hi @rbrettj 

IIRC, this behaviour was introduced by Apple in iOS 8. It also occurs on devices as well as the simulator. The solution is to use relative paths for file access, rather than absolute paths.

Hopefully the attached (simple) demo will help.

[MyTestApp.zip](https://github.com/dotnet/docs-maui/files/11016530/MyTestApp.zip)

**Comment by rbrettj** [comment]
@davidbritch, I see nothing in the documentation that states that this behavior occurs on actual devices as well as the simulator. In fact, the page in question specifically calls this out as simulator behavior. If it does occur on both, the page NEEDS to be updated to include this. Also, I see no official source, and I don't include your memory. Can this be reopened until an appropriate solution is completed? I don't feel a single response is enough to call this done...

**Comment by davidbritch** [comment]
@rbrettj I'll re-open and call out that it's also the behaviour on devices. We can't give a source because it's Apple behaviour, and they lack documentation on this.

**Comment by rbrettj** [comment]
Fair enough on not being able to provide documentation. If you can't; you can't. Once the page has been updated, that will satisfy me. Thanks.

**Comment by davidbritch** [comment]
Note for posterity: the application ID (or app's UUID) always changed for over the air updates (TestFlight, App Store) but originally didn't change for deployments from Xcode. However, Xcode 6 introduced the app's UUID changing on each build/deployment. So the doc presumably called this out because it was new behaviour for simulator deployments at the time.
