### ISSUE TITLE
HAXM is archived

### ISSUE THREAD

**Issue by dmenne** [dotnet/docs-maui#1433]
[Enter feedback here]

HAXM (https://github.com/intel/haxm/releases) is archived now - What is the alternative?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9627ff9-5d98-7114-f57c-2ef9feba2f51
* Version Independent ID: d9627ff9-5d98-7114-f57c-2ef9feba2f51
* Content: [Enable hardware acceleration for the Android emulator (Hyper-V & HAXM) - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/emulator/hardware-acceleration?view=net-maui-7.0)
* Content Source: [docs/android/emulator/hardware-acceleration.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/emulator/hardware-acceleration.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dmenne 

The Android emulator is produced/owned by Google, so the source of truth for what it supports is Google's docs. In this case: https://developer.android.com/studio/run/emulator-acceleration#vm-windows

Reading the docs, it looks like HAXM has been replaced by the Android Emulator Hypervisor Driver (AEHD).

So yes, our docs need an update to reflect the fact that HAXM is no longer supported. I'll create another issue for that.

An alternative is to use the Windows Subsystem for Android. The docs don't mention it yet because there's still work to be done to make it work smoothly. However, it can be made to work. See https://marketplace.visualstudio.com/items?itemName=Redth.WindowsSubsystemForAndroidVisualStudioExtension and https://learn.microsoft.com/en-us/shows/on-net/debug-android-apps-with-wsa-and-visual-studio-2022

Hope this helps!
