### ISSUE TITLE
There is no AndroidResource build action in Maui

### ISSUE THREAD

**Issue by plequere-ms** [dotnet/docs-maui#1500]
The "Selective Backup" section appears to have been copied and pasted from the old Xamarin docs. There is no AndroidResource build action in Maui. The build action should be left as None.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8f68de5-3f19-8731-e8ec-c9a40f85b3e3
* Version Independent ID: d8f68de5-3f19-8731-e8ec-c9a40f85b3e3
* Content: [Secure storage - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/secure-storage?tabs=android)
* Content Source: [docs/platform-integration/storage/secure-storage.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/secure-storage.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 92649](https://dev.azure.com/msft-skilling/Content/_workitems/edit/92649)

**Comment by davidbritch** [comment]
Hi @plequere-ms 

There is an AndroidResource build action:

![image](https://github.com/dotnet/docs-maui/assets/8092460/c61698af-3bdc-451d-95a0-5d01c97fff13)

I think the issue here is that the text wasn't fully updated in the move from Xamarin.Essentials to .NET MAUI. What currently says "Create a new XML file named auto_backup_rules.xml in the Resources/xml directory..." should be "Create a new XML file named auto_backup_rules.xml in the Platforms/Android/Resources/xml directory..."

**Comment by plequere-ms** [comment]
Hi @davidbritch.

I don't see this option.

![image](https://github.com/dotnet/docs-maui/assets/48521719/93a4b5c7-1708-4c53-9c04-1655610e700e)

I also checked colors.xml and the properties are as follows:

![image](https://github.com/dotnet/docs-maui/assets/48521719/18f962d2-9121-4e26-83ea-f81ea134c614)

They're default properties. The settings in colors.xml do work.

**Comment by davidbritch** [comment]
Hi @plequere-ms 

I just created a new MAUI project in 17.6.1 and looked at the build actions available on colors.xml. There are multiple Android* properties, which is what I'd expect:

![image](https://github.com/dotnet/docs-maui/assets/8092460/5835accf-14fe-4c5b-a8f6-e079243708d7)

**Comment by davidbritch** [comment]
To clarify, AndroidResource was already set as the build action on colors.xml.

**Comment by plequere-ms** [comment]
Okay, I got to the bottom of this. 

The AndroidResource Build Action only shows up if the project targets Android in a generic manner:

`	<TargetFrameworks>net7.0-android;net7.0-ios</TargetFrameworks>
`

It does not show up if I target a specific version, such as:

`    <TargetFrameworks>net7.0-ios;net7.0-android33.0</TargetFrameworks>`

Is this a bug or a feature?

**Comment by davidbritch** [comment]
It's a known issue (whether it's a bug or feature is debatable), which is why it gets no mentions in the docs. When you use `net7.0-android` it picks the default for you, which right now is `net7.0-android33.0`. The recommendation from the engineers (discussed last week) is to always use `net7.0-android`.

**Comment by davidbritch** [comment]
@plequere-ms After discussing this internally, it's apparently a bug that needs logging on Developer Community.

**Comment by plequere-ms** [comment]
Thank you.

https://developercommunity.visualstudio.com/t/MAUI-build-actions-such-as-AndroidResou/10374447?port=1026&fsid=f4432318-c7f0-4e51-b206-6cd771ecd7f9

**Comment by mcmcelro** [comment]
This bug is worse than just specifying a particular version of Android. In my project, if I use:

`<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>`

I see several Android-specific build actions (AndroidAsset, AndroidBoundLayout, AndroidNativeLibrary, AndroidResource, AndroidAotProfile, AndroidGradleProject, ...).

However, if I swap it so that Android is not the first item:

`<TargetFrameworks>net9.0-ios;net9.0-android</TargetFrameworks>`

Suddenly, all of those Android-specific build actions vanish and the files in Platforms\Android\Resources all get a build action of None.

**Comment by mcmcelro** [comment]
Additionally, all of the tooling for Android platform-specific files, like the UI builder for Android layouts, was unavailable unless **net9.0-android** was listed first.
