### ISSUE TITLE
Missing rationale for suggested better alternative to BoxView

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/docs-maui#1632]
This page contains the statement:
> Although [BoxView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.boxview) can mimic simple graphics, a better alternative is to use .NET MAUI Shapes or [.NET MAUI Graphics](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/).

A rationale for this is lacking, and adding a rationale would help to understand it the reasoning / learn better.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52947a8f-6de5-7b26-4741-65af7175c745
* Version Independent ID: 52947a8f-6de5-7b26-4741-65af7175c745
* Content: [BoxView - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/boxview)
* Content Source: [docs/user-interface/controls/boxview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/boxview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @hansmbakker 

It's historical really. In Xamarin.Forms 1, the `BoxView` control was added to draw squares/rectangles/borders. People used large numbers of them to simulate all kinds of shapes - rotating and translating a lot of them to draw more complex shapes. But each `BoxView` (at that time) represented two views in the view hierarchy, and it was possible to soon run into performance issues (particularly on Android).

Since then, Xamarin.Forms gained Shapes (draw anywhere on the page), and .NET MAUI gained Graphics (draw anywhere within a canvas). Either represent a better approach to drawing in .NET MAUI. 

`BoxView` is really only present in .NET MAUI now for Xamarin.Forms users who are migrating their apps.
