### ISSUE TITLE
You have to start telling how the ICanvas instance is acquired

### ISSUE THREAD

**Issue by AndersBillLinden** [dotnet/docs-maui#1633]
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/

does not start in the right end.

Should I only paint in an event handler and which event handler?

---
[Associated WorkItem - 157524](https://dev.azure.com/msft-skilling/Content/_workitems/edit/157524)

**Comment by davidbritch** [comment]
Hi @AndersBillLinden 

It's a fair comment. The docs were originally written that way because .NET MAUI Graphics is agnostic of the framework it's being used with. It could be used in .NET iOS apps, .NET Android apps, UWP apps, WPF apps, and many more. Each platform had a different approach to actually consuming .NET MAUI Graphics, so the decision was made to not mention that in the Graphics docs.

In .NET MAUI, Graphics is consumed via the `GraphicsView`, and those docs tell you how to get an `ICanvas` and what event handler to use.

But you're right, the docs need an update now because the reality is .NET MAUI Graphics will only be used in .NET MAUI apps, so the docs should lead with some of the details from the GraphicsView doc.
