### ISSUE TITLE
What's the timeframe on temporarily installing SQLitePCLRaw.bundle_green?

### ISSUE THREAD

**Issue by ClubAssist-PatrickBoyer** [dotnet/docs-maui#1637]
[Enter feedback here]
Per the title, the section SQLitePCLRaw.bundle_green, mentions an instruction to _temporarily_ install SQLitePCLRaw.bundle_green to install the underlying dependency that exposes SQLite on each platform. Fair enough. I understand that. What's missing is why and for how long.

Can you please provide context on what makes it temporary? I want to know what are the conditions I should be looking for to remove the dependency. Is there something in the works in sqlite-net-pcl or MAUI we should be following?

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73164f27-28e1-7bf6-64ec-277ade9ac973
* Version Independent ID: 73164f27-28e1-7bf6-64ec-277ade9ac973
* Content: [.NET MAUI local databases - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/database-sqlite)
* Content Source: [docs/data-cloud/database-sqlite.md](https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/database-sqlite.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 157526](https://dev.azure.com/msft-skilling/Content/_workitems/edit/157526)

**Comment by davidbritch** [comment]
Hi @ClubAssist-PatrickBoyer 

The issue is this. sqlite-net-pcl has a dependency of SQLitePCLRaw.bundle_green >= 2.04. But for SQLitePCLRaw.bundle_green to work with .NET MAUI, you need >= 2.1.0. Once sqlite-net-pcl gets a new release that specifies the correct version for the dependency, there'll be no need to install SQLitePCLRaw.bundle_green yourself.

**Comment by ClubAssist-PatrickBoyer** [comment]
> Hi @ClubAssist-PatrickBoyer
> 
> The issue is this. sqlite-net-pcl has a dependency of SQLitePCLRaw.bundle_green >= 2.04. But for SQLitePCLRaw.bundle_green to work with .NET MAUI, you need >= 2.1.0. Once sqlite-net-pcl gets a new release that specifies the correct version for the dependency, there'll be no need to install SQLitePCLRaw.bundle_green yourself.

Thank you! The extra context is much appreciated and helps me with planning.

Happy .NET 8 Day and congratulations on the release.

**Comment by davidbritch** [comment]
@ClubAssist-PatrickBoyer FYI, we're going to switch to recommending Microsoft.Data.Sqlite instead. The doc should be updated by the end of the month.

**Comment by davidbritch** [comment]
@ClubAssist-PatrickBoyer Scrap my last statement.

**Comment by usefulBeeing** [comment]
Just came here from this [SO conversation](https://stackoverflow.com/a/77105339/2093880). According to a recent comment, this issue has been fixed with the [v1.9.172](https://github.com/praeclarum/sqlite-net/releases/tag/v1.9.172) release. Can someone please confirm that from this release and up, SQLitePCLRaw.bundle_green is no longer needed?! Thank you.
