### ISSUE TITLE
Add info that duplicate image filename errors can occur when a png and svg have the same name

### ISSUE THREAD

**Issue by E4est** [dotnet/docs-maui#1883]
### Type of issue

Missing information

### Description

The provided information on why the duplicate image filename errors might occur helped me find the issue in our project, but maybe an addition could help people in the future a bit faster.

If there are two files named `dotnet_bot.png` and `dotnet_bot.svg`, the error will also occur.

In our case we had these two entries

```xml
    <MauiImage Include="Resources\Images\PNG\*" />
    <MauiImage Include="Resources\Images\SVG\*" BaseSize="512" />
```

and since our images are in seperate folders, the source of the issue wasn't clear immediately.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/troubleshooting?view=net-maui-8.0#duplicate-image-filename-errors

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/troubleshooting.md

### Document Version Independent Id

1cdfd37b-a119-da4e-a56e-a60dde31bb18

### Article author

davidbritch

---
[Associated WorkItem - 183661](https://dev.azure.com/msft-skilling/Content/_workitems/edit/183661)

**Comment by davidbritch** [comment]
Good catch. Fundamentally this occurs because SVG files are converted into PNGs when the app is built. Then, on some platforms all of the images are placed in the same folder in the app package, regardless of how they're structured in the VS solution. Hence the naming collision. 

Anyway, I'll get the doc updated.
