### ISSUE TITLE
Error thrown building Xamarin to Maui preferences

### ISSUE THREAD

**Issue by brianjtools** [dotnet/docs-maui#1895]
### Type of issue

Missing information

### Description

[Enter feedback here]
Using the code from the article with the appropriate files in place to convert the Xamarin to Maui preferences for Windows I get 👍 
Error	CS0246	The type or namespace name 'PropertiesDeserializer' could not be found (are you missing a using directive or an assembly reference?)
Because of course LegacyApplication.cs does not know where the PropertiesDeserializer file is located for Windows (or the other platforms for that matter). and there is no code or information on how to set it up so the platform knows that the  PropertiesDeserializer.cs in the Platforms/Windows folder.  What am I missing or is it an omission from the documentation?

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/migration/app-properties?view=net-maui-7.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/migration/app-properties.md

### Document Version Independent Id

41c5a7fb-6544-9b44-fff1-671a40d9dfc6

### Article author

davidbritch

### Metadata

* ID: 41c5a7fb-6544-9b44-fff1-671a40d9dfc6 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @brianjtools 

I just took a look at the doc, and my solution, and the doc is correct. The key to making it work is to ensure that all the classes are in the same namespace. The `LegacyApplication` class is in the `MigrationHelpers` namespace. Similarly, the `PropertiesDeserializer` class on each platform is also in the `MigrationHelpers` namespace. That way, regardless of the location of the helper classes in the solution, everything will resolve correctly because all the helper classes are in the same namespace.

Hope this helps!
