### ISSUE TITLE
Ad hoc .apk documentation publish to .aab bundle format?

### ISSUE THREAD

**Issue by heron1** [dotnet/docs-maui#1989]
### Type of issue

Possibly incorrect steps in documentation

### Description

I'm new to android development and I'm following the instructions listed in the provided documentation. When I tap the published .aab file on the android device I encounter an error that the GPK file is corrupted. From my research, it should be published as an .apk file not .aab, but since I'm new I'm not entirely sure if that's correct?

Could it be an issue with the documentation? I notice it falls under the ad-hoc not the Google Playstore section, and even mentions publishing as a .apk file, yet later the article shows how to publish the bundle as .aab, not .apk. Is this intended? If not, could the article possibly be corrected with how to publish the bundle as .apk? As I'm unsure how to.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-ad-hoc?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/publish-ad-hoc.md

### Document Version Independent Id

b66ab819-b8b5-6f50-186d-886a0fb7e25c

### Article author

@davidbritch

### Metadata

* ID: b66ab819-b8b5-6f50-186d-886a0fb7e25c 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

---
[Associated WorkItem - 200438](https://dev.azure.com/msft-skilling/Content/_workitems/edit/200438)

**Comment by davidbritch** [comment]
Hi @heron1 

The doc states the correct package format very early on: "By default, the package format for .NET MAUI Android release builds is AAB. To publish a .NET MAUI Android app for ad-hoc distribution requires that you first change the package format to APK" followed by instructions on how to do that.

Yes, there's a typo later on where it references an AAB rather than an APK, which I'll get fixed.

But other than that, the doc is correct.
