### ISSUE TITLE
visual studio for mac is deprecated, yet vscode instructions for anything related to maui on mac are poor :(

### ISSUE THREAD

**Issue by tamingchaos** [dotnet/docs-maui#1993]
### Type of issue

Outdated article

### Description

As noted in the title, the docs here are poor here. I have spent hours trying to use vscode to create an ios app, and its painful.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/ios/device-provisioning/automatic-provisioning?view=net-maui-8.0&tabs=vs

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/ios/device-provisioning/automatic-provisioning.md

### Document Version Independent Id

136ca791-32b6-dc5b-7baa-771283e4ae55

### Article author

@davidbritch

### Metadata

* ID: 136ca791-32b6-dc5b-7baa-771283e4ae55 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @thetownfool 

I agree with your sentiments completely. But unfortunately, there are no plans to fully doc the VSCode plugin until it nears a stable v1 release, because there's so much churn in it. At the moment it's an early preview only, hence it's 0.X version number, and is far from fully featured.

I realise this isn't want you want to hear, but afraid it's the reality right now.
