### ISSUE TITLE
期望的时间

### ISSUE THREAD

**Issue by LazyCoderSuhe** [dotnet/docs-maui#204]
想知道 MAUI 的文章什么时候完成，期待已久。期望给一个准确的时间，

Translated:
I've been wondering when maui's article will be completed, and I've been waiting for a long time. Expect to give an accurate time,

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI安装 - .NET MAUI](https://docs.microsoft.com/zh-cn/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui.zh-CN/blob/live/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. I translated your comment so that I could read it.

The translation indicated that you're speaking about this article, but I'm unsure if that is correct. This article has been completed. If you're wondering about the .NET MAUI product, that was released yesterday. The first official release of .NET MAUI was yesterday, with more updates coming soon. It still requires the preview versions of Visual Studio.

If you have more feedback related to this, you should share it on the [.NET MAUI github repository](https://github.com/dotnet/maui).

I'm going to close this question as answered. If you don't think it is, please reopen it.

Have a good day.
