### ISSUE TITLE
appicon ForegroundScale 

### ISSUE THREAD

**Issue by robvanschelven** [dotnet/docs-maui#2259]
### Type of issue

Missing information

### Description

[Enter feedback here]
I found information on Stack Overflow about the 'ForegroundScale' property, which addresses an issue with icon sizing on Android. Could you please include this information in the manual?

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?view=net-maui-8.0&tabs=android

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/app-icons.md

### Document Version Independent Id

2fc2b28d-e403-c63e-b7c4-6639fcd05a89

### Article author

@davidbritch

### Metadata

* ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 259814](https://dev.azure.com/msft-skilling/Content/_workitems/edit/259814)

**Comment by davidbritch** [comment]
Hi @robvanschelven 

Link to the stack overflow post?

**Comment by robvanschelven** [comment]
Hi david, https://stackoverflow.com/questions/73414054/net-maui-appicon-strange-scaling-on-android 
See Answer 1

**Comment by davidbritch** [comment]
@robvanschelven 

Understood your meaning now. So `ForegroundScale` does get a mention in the doc, but it's very well hidden. So yeah, it needs surfacing better (and expanding upon).

**Comment by robvanschelven** [comment]
Thanks

**Comment by bgsPortal** [comment]
It´s indeed hidden on the page i visited

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?view=net-maui-9.0&tabs=android

and gets mentioned here as to how to use it

https://github.com/dotnet/maui/issues/7305

Another suggestion is the name of the property suggests its for the foreground file only which i dont have and it still scales the appicon.svg file. So i did not pay attention to this attribute because i do not have a composed icon.
