### ISSUE TITLE
Application Version and Application Display Version descriptions look out of date

### ISSUE THREAD

**Issue by BruceHaley** [dotnet/docs-maui#2323]
### Type of issue

Outdated article

### Description

Using Visual Studio for Windows v 17.10.0 for a MAUI project, I find neither of the following 2 documentation statements to be true:

"When the value of the Application Display Version field is updated, the value of the Version field in the application view in the Info.plist file will be automatically updated."

"When the value of the Application Version field is updated, the value of the Build field in the application view in the Info.plist file will be automatically updated."

Looks like VS has a dedicated editor for Info.plist. Contrary to this documentation, I find the values in Info.plist are not updated via Project Properties.

I am left wondering what Application Version and Application Display Version are good for. Possibly they no longer have any use?

Thanks.
--Bruce

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/macios/info-plist?view=net-maui-8.0&tabs=vs

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/macios/info-plist.md

### Document Version Independent Id

ab6c3d99-57ee-94ef-f396-a7872a4bc0ad

### Article author

@davidbritch

### Metadata

* ID: ab6c3d99-57ee-94ef-f396-a7872a4bc0ad 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @BruceHaley 

I just took a look in the latest VS (17.10.4) and Application Version is updating the Build field in Info.plist (technically it isn't updating Info.plist - it's just the VS editor is reading from the .csproj). However, Application Display Version isn't updating anything in Info.plist.

This isn't affecting the build process though. The `ApplicationVersion` value is being copied to `CFBundleVersion` in the *Info.plist* file in the generated app package. Similarly, the `ApplicationDisplayVersion` value is being copied to `CFBundleShortVersionString` in the *Info.plist* file in the generated app package.

I took a look at VSMac and ApplicationVersion and ApplicationDisplayVersion both update Info.plist (Build and Version, respectively). I realise VSMac will shortly be reaching EOL, but it at least confirms the expected behaviour.

A quick search internally shows this is a bug with the VS editors. Therefore I don't see there's doc updates required. It's more a case of waiting for the VS editors bug to be fixed.
