### ISSUE TITLE
.NET MAUI 9: Feature switch to enable compiled bindings with source

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#2528]
In .NET MAUI 9, there's a `IsXamlCBindingWithSourceCompilationEnabled` feature switch that's disabled by default unless the app is built with NativeAOT, or full trimming.

More info: https://github.com/dotnet/maui/pull/24924 (targets RC2)

**Comment by jonathanpeppers** [comment]
There are a whole list of switches here:
* https://github.com/dotnet/maui/blob/net9.0/docs/design/FeatureSwitches.md

Most of these take the approach:
* By default they are off, so trying not to break anyone and keep existing behavior.
* If a project uses `TrimMode=full` (Mono, but link everything) or `PublishAot=true` (NativeAOT) all these switches are turned on in order to solve many trimming warnings. These may change behavior, which is the point of them.

Overall, I don't know if we need to document all of them in detail. @simonrozsival might want to weigh in, if some are more important than others.

**Comment by davidbritch** [comment]
@jonathanpeppers Already done via another PR (just isn't live because it's in an include file, for including in the new trimming doc).

**Comment by davidbritch** [comment]
Dupe of #2559
