### ISSUE TITLE
MVVM principle

### ISSUE THREAD

**Issue by jaworekplay** [dotnet/docs-maui#342]
Thank you for taking your time and creating the article. It is a really good read. However, in terms of MvvM Color should NEVER EVER make it to the VM. As any UI element is forbidden from VM.

Kind Regards Long Term Windows User

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9905cd00-f3a1-7bdd-d678-ef6c71fb53b7
* Version Independent ID: 9905cd00-f3a1-7bdd-d678-ef6c71fb53b7
* Content: [Data binding and MVVM - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/mvvm)
* Content Source: [docs/xaml/fundamentals/mvvm.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/fundamentals/mvvm.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jaworekplay 

You're right from an MVVM purity perspective. But without wanting to reopen the MVVM flame wars from over a decade ago, there are just as many who opt for pragmatic MVVM where UI types do make it into VMs, and implementations do fall into code-behind rather than VMs.

Thanks for your feedback.
