### ISSUE TITLE
Default build target

### ISSUE THREAD

**Issue by tonyfaull** [dotnet/docs-maui#411]
Given that the default build target is Android there is an issue with the next sentence:
"If you want to also target and run on Android in addition to Windows, navigate to the start of this article and select Android."
It implies that the default is not Android, otherwise why would you need to "select Android". Maybe the sentence needs to be tweaked a bit. (Edited per comments)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-gb/dotnet/maui/get-started/first-app?pivots=windows)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tonyfaull 

Afraid that the default build target is always Android. At the moment. That's why for new installs, if you immediately change the build dropdown to Windows it will still force you to install Android SDKs etc.

**Comment by tonyfaull** [comment]
Thanks @davidbritch. I accept that the default is Android. Then I have an issue with the next sentence:
"If you want to also target and run on Android in addition to Windows, navigate to the start of this article and select Android."
It implies that the default is not Android, otherwise why would you need to "select Android". Maybe that second sentence needs to be tweaked a bit.

**Comment by davidbritch** [comment]
Hi @tonyfaull 

Fundamentally the issue is this. If you install VS and leave the debug target as Android, VS will:

1. Make you install the Android SDK + emulator.
2. Make you create a default emulator.
3. Build and deploy to Android.

Whereas if you install VS and switch the debug target to Windows, VS will:

1. Make you install the Android SDK + emulator, because the default build target for a MAUI project is Android.
2. Build and deploy to Windows.

This is something that the product team is going to deal with.

So if I understand you correctly, would the following alteration make sense: "If you want to also target and run on Android in addition to Windows, navigate to the start of this article and select Android in the Choose your deployment device switcher."

**Comment by tripleo1** [comment]
Not the OP, but your "fundamental" explanation is better than your "alteration", and I think it should be included, maybe in a drop down or something.

I would start there for the "alteration" -- the one you gave is not really clearer.

My 2c...

**Comment by davidbritch** [comment]
Closing as the sentence was updated today.
