### ISSUE TITLE
Handler customization in platform-specific folders or files

### ISSUE THREAD

**Issue by domagojmedo** [dotnet/docs-maui#447]
> Handlers can be customized per platform by using the #ifdef compiler directive, to multi-target code based on the platform. However, you can just as easily use platform-specific folders or files to organize such code.

It would be really nice to have examples of customizing controls in platform specific folders or files. I think many users would prefer that to compiler directives approach

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6
* Version Independent ID: 70227b04-808f-1370-186b-10cfef525959
* Content: [.NET MAUI control customization with handlers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize)
* Content Source: [docs/user-interface/handlers/customize.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @domagojmedo 

Agreed. The handler doc is only temporary and due to be replaced. In the meantime, you may be able to figure it out yourself by looking at https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/configure-multi-targeting and/or https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code
