### ISSUE TITLE
Mention that Solution publish is not supported should be more prominent

### ISSUE THREAD

**Issue by emorell96** [dotnet/docs-maui#543]
Hi,

I just think the fact that you cannot publish using the solution but must use the project folder should be more prominently displayed.

This seems to be quite a common gotcha.

:)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44286466-fb54-f175-d197-7deee0db1e30
* Version Independent ID: 44286466-fb54-f175-d197-7deee0db1e30
* Content: [Publish a .NET MAUI app for iOS - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview)
* Content Source: [docs/ios/deployment/overview.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/deployment/overview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @emorell96 

When I wrote this doc, 2-3 weeks ago, I was able to publish using the solution.

**Comment by davidbritch** [comment]
Hi again @emorell96 

I just double-checked this, and I was able to do a `dotnet publish` from the solution folder. Admittedly, I was doing this using the build that will be released next week, but like I said, it also worked when I wrote the doc 2-3 weeks ago.

**Comment by emorell96** [comment]
Hi, sorry for the late reply. I was a little busy. This is when you have class libraries in the same solution. When there's multiple libraries that target net6.0 and not net6.0-ios for example, and you try to do `dotnet publish -f:net6.0-ios -c:Release`, it will fail complaining about the other libraries not targeting net6.0-ios.

**Comment by adegeo** [comment]
Really the issue is that when you run publish on a solution file, it tries to publish each project in the solution individually, which is a problem when your project targets something like .NET Standard or some other base framework like .NET 6. In those cases you must publish the app project directly.

@emorell96 does it fail for the main app project? I have a non-maui solution that has about 10 projects in it. Publish ran across all projects and those that couldn't compile for the target framework did fail, but those that could target the framework, succeeded.

**Comment by emorell96** [comment]
Exactly as you say. That was the suggestion I was making for the docs. The docs fail to mention that detail prominently enough IMO. The only reason I knew about it was because of an issue in the MAUI github.
