### ISSUE TITLE
Essentials docs are missing a macOS section; they only have iOS

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs-maui#564]
- Should we add a macOS tab?
- Should we just change the tab title to iOS\macOS?

**Comment by davidbritch** [comment]
I just chatted to one of the engineers about this and yes, you do have to duplicate the iOS Info.plist config into the MacCatalyst Info.plist file. Generally speaking, the two configs are identical so a joint iOS/macOS tab title would suffice (if there's an understandable way of clarifying that the Info.plist needs updating per Apple platform).

Hence https://github.com/dotnet/maui/blob/main/src/Essentials/samples/Samples/Platforms/iOS/Info.plist appears to be identical to https://github.com/dotnet/maui/blob/main/src/Essentials/samples/Samples/Platforms/MacCatalyst/Info.plist

However, there may be features in future whereby we need separate iOS + macOS tabs (because the config is different).
