### ISSUE TITLE
Can you update document to show how to .png as icon and splash screen

### ISSUE THREAD

**Issue by nssidhu** [dotnet/docs-maui#596]
For the icon,
I get weird box around the icon when using .png 
Can you show how to use .png as both as icon and splash screen ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Version Independent ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Content: [Add an app icon to a .NET MAUI app project - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=android)
* Content Source: [docs/user-interface/images/app-icons.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/app-icons.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
@nssidhu I think the .NET MAUI support for PNG isn't working correctly, or is only partially working. I would follow this issue in the .NET MAUI code repository: https://github.com/dotnet/maui/issues/7786 I would add a comment into that or one of the linked issues so that you can register that you too are having a problem. :(

Sorry!
