### ISSUE TITLE
Instructions for iOS Physical Device Debugging

### ISSUE THREAD

**Issue by NapalmCodes** [dotnet/docs-maui#609]
I am unable to find in the MAUI documentation instructions on using a physical device (not the simulator) for iOS debugging from Windows/Visual Studio 2022?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?WT.mc_id=friends-mauiworkshop-jamont)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @napalm684 

There are two approaches to doing this:

1. Using a feature called hot restart. This is the easy/quick approach.
2. Using Apple device provisioning. This is the harder approach.

(1) isn't doc'd yet because it doesn't work. Back in April Apple made some pretty big changes to automatic device provisioning that broke this feature. The engineers have reworked the feature, and AFAIK it's now working its way through test. Once that's done it'll find it's way into a VS preview release and will get doc'd.

(2) isn't doc'd yet but needs doc'ing. It also requires you to have a paid Apple Developer Account ($99 a year). It's essentially the approach outlined here: https://docs.microsoft.com/en-gb/dotnet/maui/ios/deployment/overview but instead of creating a distribution certificate/profile you create a development certificate/profile.

Hope this helps (for now)!

**Comment by NapalmCodes** [comment]
Just curious is hot restart close to release?

**Comment by davidbritch** [comment]
@napalm684 Very very close. This week. Afraid the doc will be later this month though.

**Comment by davidbritch** [comment]
I'm going to close this issue, not because the work is done. More that the work is being tracked by #764 and #384.
