### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#671]
.NET MAUI supports DI through Microsoft.Extensions.DependencyInjection.

Doc the usual DI scenarios for use in .NET MAUI apps, including injecting pages.

Use factory methods for registering services if you want to avoid using reflection at startup. See https://github.com/dotnet/maui/pull/16741 and https://github.com/dotnet/maui/pull/17004

Content:
- Fundamentals
- Explains what's in MauiProgram.cs by default
- Registering a service and consuming from pages/viewmodels.
- Limitations of DI with XAML. See https://github.com/dotnet/maui/issues/11485

---
[Associated WorkItem - 196506](https://dev.azure.com/msft-skilling/Content/_workitems/edit/196506)

**Comment by davidbritch** [comment]
https://github.com/dotnet/docs-maui/issues/1484

**Comment by Eilon** [comment]
@davidbritch ah thanks I didn't see this issue. I think another worthwhile task is improving the 'SEO' of this topic from the .NET MAUI side. I _thought_ I'd seen the MAUI DI doc you linked, but this search doesn't seem to find it (probably because it's in a different doc set? architecture vs. maui?): https://learn.microsoft.com/en-us/search/?scope=.NET%20MAUI&view=net-maui-8.0&terms=dependency%20injection

So perhaps we could at least add a TOC entry for DI in the MAUI docs that has placeholder content to link to the full DI doc? Or reverse it?

**Comment by davidbritch** [comment]
@Eilon While it's possible, from a users perspective, to have a link in a TOC to content in another docset, it's not as straightforward as just adding a link into the TOC. I won't bore you with the details. But ultimately we can do a better job of linking into the architecture content. I'll create a separate issue for that (https://github.com/dotnet/docs-maui/issues/1925), which I'll deal with in Dec.

**Comment by Eilon** [comment]
@davidbritch understood. I was thinking in the MAUI docs we would have a real doc item in place, but the content is just a paragraph or two and then says "Go to the arch docs HERE to learn more" so we wouldn't jump people around directly from the TOC.

**Comment by davidbritch** [comment]
@Eilon I should have explained my thinking. I see two work items here:

1. Adding the enterprise book to the MAUI TOC, for better discoverability - which is https://github.com/dotnet/docs-maui/issues/1925
2. Adding a DI doc to the MAUI docset, which is this issue. We need our own DI doc because there are some gaps in the enterprise DI doc.
