### ISSUE TITLE
FilePicker MacOS/iOS says Enable iCloud capabilities, but gives no indication of how to do this.

### ISSUE THREAD

**Issue by julianadormon** [dotnet/docs-maui#786]
FilePicker MacOS/iOS says, "Enable iCloud capabilities", but gives no indication of how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c527464b-c10d-4b13-10ed-aa07ed838651
* Version Independent ID: c527464b-c10d-4b13-10ed-aa07ed838651
* Content: [File picker - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-picker?tabs=ios)
* Content Source: [docs/platform-integration/storage/file-picker.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/file-picker.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 57840](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57840)

**Comment by adegeo** [comment]
Hello @julianadormon sorry for that. I believe it's supposed to link to https://docs.microsoft.com/en-us/xamarin/ios/platform/document-picker#enabling-icloud-in-xamarin but I'm not sure. I think that's why the link was omitted originally, because in .NET MAUI, I'm not sure where this actually is supposed to be. I'll ask around, but for now, you can try that link.

**Comment by davidbritch** [comment]
To be done once I update the entitlements/capabilities content.
