### ISSUE TITLE
The sample code "Launcher.Default.OpenAsync(new OpenFileRequest" int documentation not working

### ISSUE THREAD

**Issue by leungkimming** [dotnet/docs-maui#825]
Hi,

I am new to MAUI. I am building a MAUI app for user to download files (pdf, txt, word, excel) they wish and view it in their mobile's native viewer (if installed). I followed the sample in [https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/launcher?tabs=ios#open-another-app-via-a-file](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/launcher?tabs=ios#open-another-app-via-a-file) and have add below in IOS platform info.plist.
```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>file</string>  
</array>
```
`bool supportsUri = await Launcher.Default.CanOpenAsync("file://")` is giving a "true"!

It works in Android emulator with "Hello World" shown. However, in IOS emulator (iphone SE 3rd gen) IOS 15.4, I only got below!
![image](https://user-images.githubusercontent.com/37495937/186364722-2cf48bfc-d322-42d2-8f01-4befc33823b4.png)

Both "More" and "Edit Action" don't have anything to add.

Am I missing something? Please kindly offer help!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18807604-a4a8-7fa5-b675-5be77277e158
* Version Independent ID: 18807604-a4a8-7fa5-b675-5be77277e158
* Content: [Launcher - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/launcher?tabs=android)
* Content Source: [docs/platform-integration/appmodel/launcher.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/appmodel/launcher.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
I'm not sure exactly what is wrong. It seems the documentation is correct and perhaps there is a bug in .NET MAUI? Or is there a problem with iOS and that scheme? I searched and found this stackoverflow question with someone having a problem with file:// 
https://stackoverflow.com/questions/66869928/add-file-to-lsapplicationqueriesschemes-in-your-info-plist-webview-react-native

They say to use `URL` instead of `file` in the plist file. Maybe that will help?

Why it tells you file:// is OK when you think it won't be, I'm not sure either. Please file a bug with the product: https://github.com/dotnet/maui/issues
