### ISSUE TITLE
Animations doc is obsolete.

### ISSUE THREAD

**Issue by marcoablanco** [dotnet/docs-maui#929]
Animations docs shows commit as Xamarin.Forms did:

`animation.Commit(this, "SimpleAnimation", 16, 2000, Easing.Linear, (v, c) => image.Scale = 1, () => true);`

but Maui use IAnimationManager:

`public void Commit(IAnimationManager animationManger);`

[CustomAnimation](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/animation/custom.md)

**Comment by marcoablanco** [comment]
Ok, there are two animation class:

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Animation.cs
https://github.com/dotnet/maui/blob/main/src/Core/src/Animations/Animation.cs

The documentation is about first?

**Comment by davidbritch** [comment]
Hi @marcoablanco 

You should be using the `Animation` class in Controls, rather than Core. Controls.Animation consumes Core.Animation. If you look at https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Animation.cs you'll see it derives from `BaseAnimation`, which is actually https://github.com/dotnet/maui/blob/main/src/Core/src/Animations/Animation.cs.
