### ISSUE TITLE
MauiIcon

### ISSUE THREAD

**Issue by githubgoucho** [dotnet/docs-maui#966]
MauiIcon entry in project file does not work on android!
I tried:
```
	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\dblogo.png" BaseSize="128,128" />
    <MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'"
                  Include="Resources\AppIcon\dblogo.png" ForegroundFile="Resources\AppIcon\appiconfg.svg" TintColor="#40FF00FF" />
```
...
The generated AndroidManifest.xml ignores this setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Version Independent ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Content: [Change the app icon - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=windows)
* Content Source: [docs/user-interface/images/app-icons.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/app-icons.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Which setting is being ignored? An individual attribute or the whole MauiIcon with the conditional? If it's the whole line, does it work if you remove the first MauiIcon? I would be concerned that if the first item processes, the locks down the resource identifier (the path to the file) and if the second item runs afterwards, it can't generate because it's already taken. 

I just remembered some notes I put into the article about this scenario: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=windows#use-a-different-icon-per-platform

It says that you should put the conditional items BEFORE the non-conditional item. Only the first <MauiIcon> item is ever processed.

I think this should solve your problem. I'll close this as solved but let me know either way.

Also, make sure you update to the latest preview release of Visual Studio 2022 with .NET 7. There are a bunch of icon fixes 
 in .NET MAUI for .NET 7.
